### ISSUE TITLE
the Issue about the pom.xml and Test Code

### ISSUE THREAD

**Issue by yeyanzhao** [LCTL/spring-webmvc-rythm#4]
Hi, Lawrence!
Thanks for your hard work on this rythm-spring project. I want to integrate rythm to my spring app. And found this plugin. I got the code to locale and import it by maven. 
But when I run maven test, There were one error like this:
17:42:41.047 [main] ERROR o.s.s.c.SecurityNamespaceHandler - Failed to load required web classes
java.lang.ClassNotFoundException: org.springframework.security.web.FilterChainProxy
    at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.6.0_33]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.6.0_33]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.6.0_33]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.6.0_33]
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[na:1.6.0_33]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.6.0_33]
    at org.springframework.util.ClassUtils.forName(ClassUtils.java:257) ~[spring-core-3.1.0.RELEASE.jar:3.1.0.RELEASE]
    at org.springframework.security.config.SecurityNamespaceHandler.loadParsers(SecurityNamespaceHandler.java:145) [spring-security-config-3.1.0.RELEASE.jar:3.1.0.RELEASE]
    at org.springframework.security.config.SecurityNamespaceHandler.init(SecurityNamespaceHandler.java:127) [spring-security-config-3.1.0.RELEASE.jar:3.1.0.RELEASE]

I resolve it by adding one new dependency to pom.xml like this:
        <dependency>
               <groupId>org.springframework.security</groupId>
               <artifactId>spring-security-web</artifactId>
               <version>${dependency.spring.version}</version>
      </dependency>

And final there were three test failed.

Results :

Failed tests: 
  normalMessageZhTest(com.ctlok.springframework.web.servlet.view.rythm.test.MessageTagTest)
  messageWithArgumentZhTest(com.ctlok.springframework.web.servlet.view.rythm.test.MessageTagTest)
  messageWithLocaleTest(com.ctlok.springframework.web.servlet.view.rythm.test.MessageTagTest)

Tests run: 16, Failures: 3, Errors: 0, Skipped: 0

While I add one new line to the method  "renderTemplate" in class WebBaseTest, 
response.setCharacterEncoding("utf-8");  
then it will run all successfully. 

I don't know why it come to this in my computer.
The OS is win 7 Chinese which I use. 
Maybe it can be improved by using some configuration or other approach. 
I just find these problem. 

Many thanks for your hard work.

**Comment by LCTL** [comment]
Thanks you report this issue. 

MessageTagTest running on my PC is OK. 
May be default character encoding problem?

I follow your solution to fix it.

**Comment by yeyanzhao** [comment]
yes, the default characterEncoding which response gets is "ISO-8859-1", and for the zh chars, they use "utf-8".
